@startuml "use-case"
left to right direction
actor client 
actor admin 

package Ferramentas  {

     usecase "Criar Orçamento" as 1
    usecase "Criar Metas"    as 2
    usecase "Criar Planejamento" as 3
    usecase "Gerar Relatorios" as 4
    usecase " Adcionar Despesas" as 5
    usecase "Controlar Despesas" as 6
    usecase "Editar Metas" as 7             
    usecase "Editar Planejamento" as 8
    usecase "Adcionar Receitas" as 9
    usecase "Controlar Receitas" as 17
    usecase "Inserir Renda" as 10 
    usecase "Inserir Dados" as 11
    usecase "Criar Conta" as 15
    usecase "Excluir Conta" as 16

    
}

package Control{

   
    usecase "Listar Usuários" as Lu 
    usecase "Adcionar Usuario" as 12
    usecase "Remover Usuario" as 13
    usecase "Visualizar Usuarios" as 14

}
client --> 1
client --> 2
client --> 3
client --> 4
client --> 5
client --> 6
client --> 7
client --> 8
client --> 9
client --> 10
client --> 11
client --> 15
client --> 16
client --> 17
admin --> Lu
admin --> 12
admin --> 13
admin --> 14






@enduml

