@startuml

package "CoinKeep" {

  abstract Client {
    - name: string
    - email: string
    - password: char
    - data_nascimento: char
    - sexo: string
   
    
  }

  class Receita {
    - description: string
    - value: int
    - date: char
  }

  class Despesa {
    - description: string
    - value: int
    - date: char
    - category: string
  }

  class Meta {
    - description: string
    - value: int
    - date: char
    
  }

  class Relatorio {
    - title: string
    - date: char
    - Content: string
  }

  class Planejamento {
    - renda: int
    - Deadline: int
    - orçamento: int
  }
  

 class Comprar_Plano{
  - value: int
  - name: string
 }

  
  Class Criar_Conta{
    - nome: string
    - email: string
    - Data: char
  }
 Planejamento -- Receita
 Planejamento -- Despesa
 Client -- Planejamento
 Planejamento-- Meta
Planejamento -- Relatorio
 Client -- Criar_Conta
 Client -- Comprar_Plano

}

@enduml