@startuml

package "CoinKeep" {

  abstract Client {
    - name: string
    - email: string
    - password: char
    - data_nascimento: char
    - sexo: string
    - renda: int
    
  }

  class Receita {
    - description: string
    - value: int
    - date: char
  }

  class Despesa {
    - description: string
    - value: int
    - date: char
    - category: string
  }

  class Meta {
    - Objetivos_Financeiros: string
    - description: string
    - Value: int
    - date: char
    
  }

  class Relatorio {
    - Title: string
    - date: char
    - Content: string
  }

  class Planejamento {
    - Objective: string
    - Deadline: int
    - Steps: string
    - Resources: string
  }
  class categoria{
      - name: string
  }

  class Renda{
    - valor: int
    - Mensal: int
    - Semanal: int 
    - Diaria: int
    
  }

  class Excluir_Conta{
    - nome: string
    - email: string
    - Data: char

  }
  Class Criar_Conta{
    - nome: string
    - email: string
    - Data: char
  }
 Client -- Receita
 Client -- Despesa
 Client -- Planejamento
 Client -- Meta
 Client -- Relatorio
 Despesa -- categoria
 Client -- Renda
 Client -- Excluir_Conta
 Client -- Criar_Conta

}

@enduml